### ISSUE TITLE
Add a timeout option

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#83] opened 2020-09-04 05:39 UTC
For instance, if there has been no movement for an hour allow a timeout to stop collecting. In the case the user has gone home to bed and forgot to stop collecting. That way he can optionally create a timeout if he has such a bad habit.

**Comment by zamojski** [comment] 2020-09-04 06:00
Duplicate of #6.

**Closed by zamojski** 2020-09-04 06:00 UTC
Labels: duplicate, enhancement
