### ISSUE TITLE
App doesn't work where I stay 

### ISSUE THREAD

**Issue by x64x2** [zamojski/TowerCollector#216] opened 2023-12-10 10:21 UTC
It takes days to load , I've been waiting literally weeks for app to receive gps coordinates and it hasn't done sh*t
I had to switch mobile twice as to ascertain whether it's from my mobile or from the app . The app frustrated me so much I ended up taking a toll on my phone

**Comment by zamojski** [comment] 2023-12-12 07:58
Please share some details which phones and which Android version did you test.

You may try to disable GPS Optimizations in Collector Preferences within the app and see if that helps.

Would be very helpful to share diagnostic logs - https://github.com/zamojski/TowerCollector/blob/master/FAQ.md#how-to-enable-diagnostic-logging . If you're concerned about privacy please gather the logs while not being at home because it may contain GPS traces.

**Comment by krutoivoker** [comment] 2024-01-06 13:21
At several locations around of my city I saw similar issues with GPS inavailability. As I understood, all the issues was caused by a technical limitations or special equipment like pocket jammers, wireless Chinese amplifiers of everything etc.

**Comment by zamojski** [comment] 2024-08-28 20:06
Closing as no reply from reporter.

**Closed by zamojski** 2024-08-28 20:06 UTC
Labels: help wanted
