### ISSUE TITLE
Locked at "GPS status: initializing"

### ISSUE THREAD

**Issue by drzraf** [zamojski/TowerCollector#67] opened 2019-11-20 14:39 UTC
... then it shows `GPS status: no location`, and then only starts collecting data (TC 2.0.8 on Android 7)
That behavior creates confusion (and I also don't know why it failed to gather GPS status/location)

**Comment by zamojski** [comment] 2019-11-22 20:52
Can you enable logging on diagnostic/debug level in application advanced preferencesand attach the file here?

**Comment by drzraf** [comment] 2019-11-23 02:29
Where's that debug file located?

**Comment by zamojski** [comment] 2019-11-23 16:31
It will be created on internal memory / sd card inside Tower Collector folder.

**Comment by zamojski** [comment] 2019-11-30 14:09
@drzraf Did you manage to generate log file?

**Comment by zamojski** [comment] 2020-02-02 12:36
Closing as cannot reproduce.

**Closed by zamojski** 2020-02-02 12:36 UTC
Labels: help wanted

**Comment by drzraf** [comment] 2020-02-02 17:02
Sorry. Just to complete: My observation is that GPS is not starting until I leave WiFi connection and get with 4G.

**Comment by zamojski** [comment] 2020-02-03 10:33
Some phones, especially cheap ones, have problem initializing GPS when it's not constantly enabled and used very rarely. I've several phones to test my application (most of then really cheap, based on MediaTek components) and they have similar problem when not used for couple of days but the phone I use on daily basis finds GPS fix in seconds.

You can try to use [GPS Data app](https://play.google.com/store/apps/details?id=com.pierwiastek.gpsdata) to see if it seeks and finds any satellites. According to GPS standard it may take up to 11 minutes to calculate the location if the satellites signal is strength enough.
