### ISSUE TITLE
Fail to collect measurements from both SIMs in dual-SIM configuration

### ISSUE THREAD

**Issue by som89** [zamojski/TowerCollector#129] opened 2021-07-23 08:13 UTC
When I inserted two SIMs in my Sony Xperia XA2, only one of them is used to collect the cell towers.

If I remove either of the SIMs, it work fine as usual. 

Something else that seems weird is that the number of measurement has increased by factor ~10 with two SIMs, e.g. a new measurement is made every 5-10 seconds even if I don't move, while it was only after a long move before, with a single SIM.

I'm using LineageOS 18.1 with microG (that also means that I cannot test by soft disabling one SIM card).

**Comment by zamojski** [comment] 2021-07-28 20:52
The best would be if you could enable diagnostic logging and attach the log file here.

https://zamojski.info/FAQ,Tower-Collector.html#EnableDiagnosticLogging

**Comment by som89** [comment] 2021-07-28 22:20
Here it is. For a couple of minutes I did not move.

[2021-07-29-01-10-39.log](https://github.com/zamojski/TowerCollector/files/6896754/2021-07-29-01-10-39.log)

**Comment by zamojski** [comment] 2021-07-30 05:15
I've reviewed the logs and the problem with collecting data from both SIM cards is caused by Android API returning invalid data, the LTE cell info is correct but the WCDMA doesn't provide MNC (null which is converted to UNKNOWN=2147483647 on app side).
`Invalid CellIdentityWcdma [mcc=250, mnc=2147483647, lac=842, cid=7673024, psc=273]`
The full set of reported cells looks like this. It's typical that mRegistered=NO are invalid but the mRegistered=YES should be correct.
```
[
    # DISCARDED DUE TO MISSING MNC # CellInfoWcdma:{mRegistered=YES mTimeStamp=881457362359154ns mCellConnectionStatus=2147483647 CellIdentityWcdma:{ mLac=842 mCid=7673024 mPsc=273 mUarfcn=2987 mMcc=250 mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthWcdma: ss=-85 ber=99 rscp=2147483647 ecno=2147483647 level=3}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoWcdma:{mRegistered=NO mTimeStamp=881457362359154ns mCellConnectionStatus=2147483647 CellIdentityWcdma:{ mLac=2147483647 mCid=2147483647 mPsc=281 mUarfcn=2987 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthWcdma: ss=-81 ber=99 rscp=2147483647 ecno=2147483647 level=3}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoWcdma:{mRegistered=NO mTimeStamp=881457362359154ns mCellConnectionStatus=2147483647 CellIdentityWcdma:{ mLac=2147483647 mCid=2147483647 mPsc=297 mUarfcn=10762 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthWcdma: ss=-97 ber=99 rscp=2147483647 ecno=2147483647 level=2}, 
    # VALID # CellInfoLte:{mRegistered=YES mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=129681668 mPci=442 mTac=21850 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=250 mMnc=99 mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-69 rsrp=-99 rsrq=-11 rssnr=2147483647 cqi=2147483647 ta=2 level=2 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=209 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-81 rsrp=-102 rsrq=-11 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=2 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=368 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-81 rsrp=-106 rsrq=-15 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=174 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-79 rsrp=-110 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=202 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-81 rsrp=-106 rsrq=-16 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=134 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-83 rsrp=-111 rsrq=-19 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=355 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-81 rsrp=-110 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=495 mTac=2147483647 mEarfcn=3300 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-83 rsrp=-111 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=37 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-67 rsrp=-94 rsrq=-18 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=3 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=4 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-67 rsrp=-101 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=2 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=315 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-69 rsrp=-95 rsrq=-16 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=3 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=498 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-67 rsrp=-98 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=2 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=143 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-69 rsrp=-101 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=2 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=322 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-67 rsrp=-99 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=2 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=185 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-83 rsrp=-114 rsrq=-20 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=1 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}, 
    # DISCARDED DUE TO MISSING ALL IDS #CellInfoLte:{mRegistered=NO mTimeStamp=881457380923477ns mCellConnectionStatus=2147483647 CellIdentityLte:{ mCi=2147483647 mPci=361 mTac=2147483647 mEarfcn=1301 mBands=[] mBandwidth=2147483647 mMcc=null mMnc=null mAlphaLong= mAlphaShort= mAdditionalPlmns={} mCsgInfo=null} CellSignalStrengthLte: rssi=-69 rsrp=-94 rsrq=-10 rssnr=2147483647 cqi=2147483647 ta=2147483647 level=3 parametersUseForLevel=0 android.telephony.CellConfigLte :{ isEndcAvailable = false }}
] 
```
Because you use custom ROM, which may not be fully following Android documentation, I think this can only be fixed by the developer of your ROM, so please report the issue there. I'm unable to help you here because I don't have a way to retrieve valid data.

Regarding the second issue with collecting data while stationary, in the log file I see that the main cell has changed.
`Distance condition not achieved but 1 main cells changed`
It definitely happens too often and also considering that there's a single valid cell it clearly indicates the issue. It's caused by invalid WCDMA cell being ignored later. So the logic thinks that there're now 2 main cells while previously we had 1 main cell and tries to save it. I will fix it in the next update.

**Comment by som89** [comment] 2021-08-02 08:35
Thank you for looking into this. The explanation makes sense.
I'll try if I can produce a logcat demonstrating the issue with the system to report it to LineageOS.
Anyway fixing the problem with too frequent cell collection will be much appreciated!

**Comment by zamojski** [comment] 2021-08-02 09:15
I've the fix ready, just need to test it :-)

**Closed** 2021-08-08 10:34 UTC
Labels: bug
