### ISSUE TITLE
[BUG] The application suddenly crashes when I click on the upload button.

### ISSUE THREAD

**Issue by sargoon** [zamojski/TowerCollector#56] opened 2019-04-26 15:27 UTC
Hi @zamojski

**Expected behavior**

The Tower Collector users need to be able to Upload something on the Tower Collector application. 

**Actual behavior**

When I click on the *upload* button, the Tower Collector application gave an error and suddenly crashes. 

**How to reproduce**

1. Open the Tower Collector app.
2. Then click on the Upload button.
3. And you will see that the application crashes suddenly.

* App version: 2.0.2
* Operating system: Android 7.0

**Recording Of The Bug**
![HappyAnchoredCockatoo-small](https://user-images.githubusercontent.com/34961616/56819098-b92ec300-6851-11e9-90df-d91b65059a65.gif)

**Logcat Report**

`E/PackageManagerCompat( 3926): Could not set installer package name for info.zamojski.soft.towercollector
E/SQLiteLog( 4700): (14) os_unix.c:32460: (2) open(/data/user/0/info.zamojski.soft.towercollector/databases/measurements.db) - 
E/SQLiteDatabase( 4700): Failed to open database '/data/user/0/info.zamojski.soft.towercollector/databases/measurements.db'.
E/SQLiteDatabase( 4700): 	at info.zamojski.soft.towercollector.c.f.a(MeasurementsDatabase.java:695)
E/SQLiteDatabase( 4700): 	at info.zamojski.soft.towercollector.SplashActivity.d(SplashActivity.java:138)
E/SQLiteDatabase( 4700): 	at info.zamojski.soft.towercollector.SplashActivity.a(SplashActivity.java:25)
E/SQLiteDatabase( 4700): 	at info.zamojski.soft.towercollector.SplashActivity$1.run(SplashActivity.java:95)
E/f       ( 4700): 	at info.zamojski.soft.towercollector.c.f.a(MeasurementsDatabase.java:695)
E/f       ( 4700): 	at info.zamojski.soft.towercollector.SplashActivity.d(SplashActivity.java:138)
E/f       ( 4700): 	at info.zamojski.soft.towercollector.SplashActivity.a(SplashActivity.java:25)
E/f       ( 4700): 	at info.zamojski.soft.towercollector.SplashActivity$1.run(SplashActivity.java:95)
F/DEBUG   ( 4727): pid: 4700, tid: 4716, name: RenderThread  >>> info.zamojski.soft.towercollector <<<
E/RecentsTaskLoader( 2194): Unexpected null component name or activity info: ComponentInfo{info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity}, null
E/RecentsTaskLoader( 2194): Unexpected null component name or activity info: ComponentInfo{info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity}, null
E/RecentsTaskLoader( 2194): Unexpected null component name or activity info: ComponentInfo{info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity}, null
E/PackageManagerCompat( 3926): Could not set installer package name for info.zamojski.soft.towercollector
E/SQLiteLog( 5074): (14) os_unix.c:32460: (2) open(/data/user/0/info.zamojski.soft.towercollector/databases/measurements.db) - 
E/SQLiteDatabase( 5074): Failed to open database '/data/user/0/info.zamojski.soft.towercollector/databases/measurements.db'.
E/SQLiteDatabase( 5074): 	at info.zamojski.soft.towercollector.c.f.a(MeasurementsDatabase.java:695)
E/SQLiteDatabase( 5074): 	at info.zamojski.soft.towercollector.SplashActivity.d(SplashActivity.java:138)
E/SQLiteDatabase( 5074): 	at info.zamojski.soft.towercollector.SplashActivity.a(SplashActivity.java:25)
E/SQLiteDatabase( 5074): 	at info.zamojski.soft.towercollector.SplashActivity$1.run(SplashActivity.java:95)
E/f       ( 5074): 	at info.zamojski.soft.towercollector.c.f.a(MeasurementsDatabase.java:695)
E/f       ( 5074): 	at info.zamojski.soft.towercollector.SplashActivity.d(SplashActivity.java:138)
E/f       ( 5074): 	at info.zamojski.soft.towercollector.SplashActivity.a(SplashActivity.java:25)
E/f       ( 5074): 	at info.zamojski.soft.towercollector.SplashActivity$1.run(SplashActivity.java:95)
E/InputDispatcher( 2101): channel '58e7e2e info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/RecentsTaskLoader( 2194): Unexpected null component name or activity info: ComponentInfo{info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity}, null
E/RecentsTaskLoader( 2194): Unexpected null component name or activity info: ComponentInfo{info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity}, null
E/RecentsTaskLoader( 2194): Unexpected null component name or activity info: ComponentInfo{info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.SplashActivity}, null
E/PackageManagerCompat( 3926): Could not set installer package name for info.zamojski.soft.towercollector
E/SQLiteLog( 5186): (14) os_unix.c:32460: (2) open(/data/user/0/info.zamojski.soft.towercollector/databases/measurements.db) - 
E/SQLiteDatabase( 5186): Failed to open database '/data/user/0/info.zamojski.soft.towercollector/databases/measurements.db'.
E/SQLiteDatabase( 5186): 	at info.zamojski.soft.towercollector.c.f.a(MeasurementsDatabase.java:695)
E/SQLiteDatabase( 5186): 	at info.zamojski.soft.towercollector.SplashActivity.d(SplashActivity.java:138)
E/SQLiteDatabase( 5186): 	at info.zamojski.soft.towercollector.SplashActivity.a(SplashActivity.java:25)
E/SQLiteDatabase( 5186): 	at info.zamojski.soft.towercollector.SplashActivity$1.run(SplashActivity.java:95)
E/f       ( 5186): 	at info.zamojski.soft.towercollector.c.f.a(MeasurementsDatabase.java:695)
E/f       ( 5186): 	at info.zamojski.soft.towercollector.SplashActivity.d(SplashActivity.java:138)
E/f       ( 5186): 	at info.zamojski.soft.towercollector.SplashActivity.a(SplashActivity.java:25)
E/f       ( 5186): 	at info.zamojski.soft.towercollector.SplashActivity$1.run(SplashActivity.java:95)
F/DEBUG   ( 5211): pid: 5186, tid: 5202, name: RenderThread  >>> info.zamojski.soft.towercollector <<<
E/InputDispatcher( 2101): channel 'e5a57ba info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
`

**Comment by zamojski** [comment] 2019-05-07 18:13
From where did you get the application? Google Play or F-Droid or somewhere else? What happens if you collect some data before using upload button?

**Comment by zamojski** [comment] 2019-07-27 08:54
Closing as cannot reproduce.

**Closed by zamojski** 2019-07-27 08:54 UTC
Labels: bug
