### ISSUE TITLE
release on F-Droid

### ISSUE THREAD

**Issue by takiainen** [zamojski/TowerCollector#25] opened 2017-02-05 20:54 UTC
If I've understood correctly, this app seems to be open source. If so, would be nice to see it added into F-Droid (open source app "store"), since majority of privacy minded people don't want to install GAPPS on their phone and thus don't have Play Store access. Currently there isn't a single app on F-Droid that collects cell towers for opencellid database, and this could be the one!

https://f-droid.org/

**Comment by zamojski** [comment] 2017-02-09 21:11
Yes, Tower Collector is an open source project. I tried to add it to F-Droid twice already but I failed on complicated process after few hours. At the moment I'm very busy with private stuff but if you know how to add it quickly please let me know and I will try.

**Comment by takiainen** [comment] 2017-02-16 09:32
I just left TowerCollection in F-Droid submission queue. It goes through a review process (which might take some time) and if accepted it will be added into F-Droid. Is it ok? https://gitlab.com/fdroid/rfp/issues/36

**Comment by est31** [comment] 2017-02-16 11:47
Hi there! I'm an f-droid packager and wanted to package this app.

I found an issue while trying to build it. Apparently the build needs `app/properties/private.properties` to be present, which I don't have. Now there are a few options:

* upload the file into git. We do our signing ourselves, so we don't need the actual signing part, only the acra keys
* Change the build to not rely on acra or add a gradle flavour that does not

Its possible that TOS for some services forbid you to publish the API keys, I don't know whether its forbidden in this case, I haven't read the TOS.

**Comment by zamojski** [comment] 2017-02-18 12:20
@takiainen Thank you!
@est31 It's not only about ACRA, there're some other confidential things like signing key defined in `private.properties` file, moreover you'll need `google-services.json` file (required by Google Analytics) to make the app one-to-one as official one. I cannot publish any of these. I'd like to understand why do you need to build it and why you cannot use existing apk file from [releases](zamojski/TowerCollector/releases)?

**Comment by est31** [comment] 2017-02-18 16:21
@zamojski see the inclusion policy https://f-droid.org/wiki/page/Inclusion_Policy

Especially: 

* f-droid builds the entire app itself to ensure the source corresponds to the actual app. no proprietary libraries are allowed
* use of google analytics is a problem, as it includes a proprietary library to be used inside the app. Maybe microg can help here, but it won't help with the api key problem

If its not okay to publish the API keys in a plain text file (they are already published inside the APK), you can try to publish it on a self hosted f-droid repository instead, like the list here: https://f-droid.org/wiki/page/Known_Repositories

**Comment by zamojski** [comment] 2017-02-19 14:40
@est31 Let me understand correctly:

1. You'll build the app directly from source code and distribute it on your own as apk?
2. In order to make my app available in f-droid I would need to remove Google Play Services dependency?
3. Should I use different Android package ID for f-droid version?

Self hosting is not an option for me because I would need to pay for a Python server.

**Comment by est31** [comment] 2017-02-19 15:01
> You'll build the app directly from source code and distribute it on your own as apk?

correct.

> In order to make my app available in f-droid I would need to remove Google Play Services dependency?

Yes, either remove it, or make it possible to build it without the dependency so that we can enable that option. Can be achieved for example with gradle flavours.

> Should I use different Android package ID for f-droid version?

Most apps on F-Droid don't do this, but if you want it for some reason, its definitely possible.

**Comment by zamojski** [comment] 2017-02-19 15:23
@est31 Thanks for clarifications. This means I need to make some of the features optional and this will take time. For next few months I will be very busy with personal matters so I will let you know once I made necessary changes.

**Comment by est31** [comment] 2017-02-19 17:44
Looking forward to it! Thanks for the support.

**Comment by krt16s** [comment] 2017-02-19 22:45
Iirc we can use mockdata for acra, however `compile 'com.google.android.gms:play-services-analytics:9.8.0'` is non-free software.

**Comment by IzzySoft** [comment] 2017-06-28 18:53
As an "interim solution" (until dependencies for the luckily strict restrictions of the official repo are solved – and if you wish so, even afterwards) TowerCollector is [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/info.zamojski.soft.towercollector) now. It will be kept up-to-date automatically as soon as a new release is tagged at this very Github project *and an `.apk` attached to it.* @zamojski could you please fill that gap for the latest release, see #30?

Of course it is definitely preferable to have an `.apk` without proprietary elements (currently I see GMS, Firebase, Google Analytics), so I strongly encourage going that path. Plus it then can be adopted into the official F-Droid repo, which is much more trustworthy than mine especially for the reasons [outlined above by est31](https://github.com/zamojski/TowerCollector/issues/25#issuecomment-280855959). I run some checks, though, to keep the "trust-gap" as small as possible :wink:

**Comment by IzzySoft** [comment] 2017-06-28 20:25
@est31 I can confirm TowerCollector works fine with microG. The GA part most likely runs into a dummy, but that's as it should be (I don't want my data there :wink:). As pointed out in my previous comment: I've adopted TC into my repo – at least until those dependencies can be solved/removed or Adam no longer wishes this. He has already filled the gap mentioned in my previous post, so it's up-to-date now.

**Comment by zamojski** [comment] 2017-07-01 07:05
@IzzySoft Thanks for hosting it in your repo! As soon as I manage to complete with removing dependency to Google Analytics I will let you know and post the code here. Right now it's still in progress.

**Comment by IzzySoft** [comment] 2018-01-07 00:01
@zamojski any progress on that (including Firebase)? Maybe a "stub" (with "dummy methods" always returning "dummy defaults" to fool the calling methods) would work. That way you wouldn't need any heavy lifting in your app's code – but some scanners (like mine) would probably still think GMS, GA and Firebase are present, so a clean approach of course would be preferred.

**Comment by zamojski** [comment] 2018-01-07 07:27
The complexity I faced is in references i gradle definitions. I didn't find
the way get rid of them conditionally. I see 2 options right now: I will
create separate branch for F-Droid build and manually remove everything
there but this is only a temporary solution as I would need to maintain two
different branches or I will try to replace Google Analytics with some open
source alternative which I'm trying to do. This issue is my main focus now.

07.01.2018 01:01 "Izzy" <notifications@github.com> napisał(a):

**Comment by zamojski** [comment] 2018-01-07 11:04
I know about flavors and the help only in code area. Half a year ago it wasn't possible to use then on gradle build files level which is the place where the reference to Google Play Services needs to be defined. I will explore the topic once again but this is the main problem.

**Comment by zamojski** [comment] 2018-01-28 10:07
If anybody knows the way to make classpath dependency optional for just flavor please share here or on [F-Droid forum](https://forum.f-droid.org/t/google-services-classpath/1970). This is the last obstacle I have on my way. The rest of changes is available on [fdroid ](/zamojski/TowerCollector/tree/fdroid) branch.

**Comment by zamojski** [comment] 2018-01-28 13:29
Seems F-Droid team has a [workaround](https://forum.f-droid.org/t/google-services-classpath/1970/2) for this problem which needs to be applied in this case.
@est31 can you please check if it's possible to build the app for F-Droid from `fdroid` branch, flavor `productionFdroidRelease`?

**Comment by zamojski** [comment] 2018-04-09 16:09
I merged the code into master. The flavor name and workaround still needs to be applied.

**Comment by IzzySoft** [comment] 2018-06-18 11:47
Guess this issue can be closed, now that TowerCollector is available at F-Droid? Please also let me know if it's OK for you that I keep it in my repo (faster updates there – but users may get confused of the "signature mismatch"; however, using a "3rd party repo" they should be aware of that).

**Comment by zamojski** [comment] 2018-06-18 17:34
I think I still need to add app description for instance but it's finally ready :) Thanks for help! I think you can keep it but please mention in the title or description that it's official Google Play Edition, just served from another source.

**Comment by IzzySoft** [comment] 2018-06-18 18:38
@zamojski I could do that, but it won't help much: the F-Droid Android client, merging that with the official repo, will display F-Droid's description. So you'd see that only on my website.

There is no Export of the settings, or did I just miss it? I'd hate having to type the OCID Api Key again, thinking about uninstalling and reinstalling from F-Droid main. Would be really nice to have when switching from Playstore to F-Droid.

If you could add that (export/import configuration) with the next version, I'd say I rather drop it from my repo to avoid confusion. Updates are not that frequent/urgent I couldn't wait a few days until they're served via F-Droid. TowerCollector is quite mature.

**Comment by zamojski** [comment] 2018-06-19 04:37
I didn't know the app record would be merged. I think it will be less confusing to have just one app in such case.

How many devices you want to migrate? Maybe I will manage to find some time later this week to do it.

**Comment by IzzySoft** [comment] 2018-06-19 15:12
> I didn't know the app record would be merged.

Ive noticed that a couple of times: while my repo had a newer version already for days, the app still marked the one from main as "leading" – because they usually [mark that as preferred](https://gitlab.com/fdroid/fdroidclient/issues/1268). It's still shown as a single entry (just the `.apk` files have a mark which repo they come from), so they can only show one description.

> How many devices you want to migrate?

Currently two active devices (using different bands: the older one has no LTE support). But I'm probably not the only one in need :wink:

**Comment by zamojski** [comment] 2018-06-20 04:19
> Currently two active devices
I thought you have more ;-) There's such function codec but it doesn't have any user interface which I would need to do quickly. Let me try and I will let you know when I have it ready.

**Comment by IzzySoft** [comment] 2018-06-20 06:18
I do have more. But you certainly wanted to know those with TC running on them :grin:

Thanks in advance, looking forward to that!

**Comment by zamojski** [comment] 2018-06-24 12:56
The option will be available in next version :)

**Closed by zamojski** 2018-06-24 12:56 UTC
Labels: question

**Comment by IzzySoft** [comment] 2018-06-24 17:03
Thanks a lot! As soon as that's available on F-Droid I'll "switch over" and then remove the app from my repo. Of course you can ping me anytime if I should put it back, in case it's needed :wink:

**Comment by IzzySoft** [comment] 2018-07-07 23:07
@zamojski just a short feedback: on one device I could successfully switch by export › uninstall › reinstall › import (preferences and database). On the second device, the last step failed for both, preferences and database. Luckily it happened in that order (or I wouldn't have dared to try it on the second device) – so I just did an `adb backup -f info.zamojski.soft.towercollector.ab -apk info.zamojski.soft.towercollector` on the first device and restored that to the second one. So far, it looks good. Will run a test tomorrow and, if that succeeds, remove TC from my repo as suggested.

Thanks again!

**Comment by zamojski** [comment] 2018-07-08 05:13
Did you check if the app has permission to access file storage? Maybe there's an issue, I forgot to check such case.

**Comment by IzzySoft** [comment] 2018-07-08 11:15
Ugh, no. On the first device a popup asked for that. On the second device it didn't. So you are probably right with that.

Thinking about it, on the very same device I had a comparable problem in the past (some app not able to write to storage). So the culprit most likely is the ROM on my device. Though, if the toast had said "cannot access storage" instead of "import unsuccessful", that would have given a pointer :wink:
