### ISSUE TITLE
mnc's for same time might be different

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#203] opened 2023-06-04 14:55 UTC
Here we observe the mnc field switches from 66 to 3 and then stays that way, not in
tune with the other fields.

```
mcc,mnc,lac,cell_id,short_cell_id,rnc,psc,asu,dbm,ta,lat,lon,accuracy,speed,bearing,altitude,measured_at,net_type,neighboring,discovered_at,device,rsrp,rsrq,rssi,rssnr,cqi,rscp,csi_rsrp,csi_rsrq,csi_sinr,ss_rsrp,ss_rsrq,ss_sinr,cdma_dbm,cdma_ecio,evdo_dbm,evdo_ecio,evdo_snr,ec_no,arfcn
515,66,4112,17111346,66841,50,74,0,-113,0,19.22354500,120.612801666667,2.8,252.11,184.63,11726,"2023-05-09T02:24:34.091Z",LTE,false,"2023-05-09T02:23:38.449Z","samsung SM-A136U",-133,-20,-113,-8,,,,,,,,,,,,,,,425
515,66,4112,17111346,66841,50,74,0,-113,0,19.22126000,120.612623333333,2.8,251.99,184.33,11729.7,"2023-05-09T02:24:35.101Z",LTE,false,"2023-05-09T02:23:38.449Z","samsung SM-A136U",-133,-20,-113,-8,,,,,,,,,,,,,,,425
515,66,4112,17111346,66841,50,74,0,-113,0,19.21899000,120.612451666667,2.8,252.34,184.25,11729.8,"2023-05-09T02:24:36.095Z",LTE,false,"2023-05-09T02:23:38.449Z","samsung SM-A136U",-133,-20,-113,-8,,,,,,,,,,,,,,,425
515,66,4112,17111346,66841,50,74,0,-113,0,19.216698333333,120.612273333333,2.7,252.53,184.37,11729.6,"2023-05-09T02:24:37.106Z",LTE,false,"2023-05-09T02:23:38.449Z","samsung SM-A136U",-133,-20,-113,-8,,,,,,,,,,,,,,,425
515,66,4112,17111346,66841,50,74,0,-113,0,19.214408333333,120.612103333333,2.7,252.77,184.35,11734.4,"2023-05-09T02:24:38.104Z",LTE,false,"2023-05-09T02:23:38.449Z","samsung SM-A136U",-133,-20,-113,-8,,,,,,,,,,,,,,,425
515,3,4112,17111346,66841,50,74,0,-113,0,19.214408333333,120.612103333333,2.7,252.77,184.35,11734.4,"2023-05-09T02:24:38.510Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.214408333333,120.612103333333,2.7,252.77,184.35,11734.4,"2023-05-09T02:24:38.510Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.212138333333,120.611926666667,3,251.49,184.09,11734.8,"2023-05-09T02:24:39.098Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.212138333333,120.611926666667,3,251.49,184.09,11734.8,"2023-05-09T02:24:39.098Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.20987000,120.61174500,3,253.08,184.51,11736.3,"2023-05-09T02:24:40.092Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.20987000,120.61174500,3,253.08,184.51,11736.3,"2023-05-09T02:24:40.092Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.207601666667,120.61156000,3.3,251.75,184.46,11737.5,"2023-05-09T02:24:41.090Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.207601666667,120.61156000,3.3,251.75,184.46,11737.5,"2023-05-09T02:24:41.090Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.205338333333,120.61137500,3.5,252.34,184.34,11738.3,"2023-05-09T02:24:42.084Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.205338333333,120.61137500,3.5,252.34,184.34,11738.3,"2023-05-09T02:24:42.084Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.203073333333,120.611198333333,3.6,252.06,184.33,11740,"2023-05-09T02:24:43.090Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.203073333333,120.611198333333,3.6,252.06,184.33,11740,"2023-05-09T02:24:43.090Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.20081500,120.61103000,3.7,251.74,184.34,11741,"2023-05-09T02:24:44.094Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.20081500,120.61103000,3.7,251.74,184.34,11741,"2023-05-09T02:24:44.094Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.19855500,120.61085500,3.8,252.27,184.2,11740.7,"2023-05-09T02:24:45.094Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.19855500,120.61085500,3.8,252.27,184.2,11740.7,"2023-05-09T02:24:45.094Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.196303333333,120.610691666667,3.9,251.39,184.24,11741.2,"2023-05-09T02:24:46.096Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.196303333333,120.610691666667,3.9,251.39,184.24,11741.2,"2023-05-09T02:24:46.096Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.194048333333,120.610516666667,4,251.47,184.29,11740.7,"2023-05-09T02:24:47.081Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.194048333333,120.610516666667,4,251.47,184.29,11740.7,"2023-05-09T02:24:47.081Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,4112,17111346,66841,50,74,0,-113,0,19.191788333333,120.61033000,4.2,251.69,184.46,11740.7,"2023-05-09T02:24:48.073Z",LTE,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",-133,-20,-113,,,,,,,,,,,,,,,,425
515,3,25024,79243247,10223,1209,0,2,-109,,19.191788333333,120.61033000,4.2,251.69,184.46,11740.7,"2023-05-09T02:24:48.073Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,
515,3,25024,79243247,10223,1209,199,2,-109,,19.189541666667,120.610156666667,4.3,250.46,183.95,11739.8,"2023-05-09T02:24:49.084Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,10562
515,3,25024,79243247,10223,1209,199,2,-109,,19.187293333333,120.60999000,4.4,250.43,184.51,11739.4,"2023-05-09T02:24:50.087Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,10562
515,3,25024,79243247,10223,1209,199,2,-109,,19.185046666667,120.60981000,4.5,250.21,184.16,11738.4,"2023-05-09T02:24:51.092Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,10562
515,3,25024,79243247,10223,1209,199,2,-109,,19.182796666667,120.609608333333,4.3,251.1,184.59,11737.8,"2023-05-09T02:24:52.086Z",UMTS,false,"2023-05-09T02:24:38.510Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,10562
```

So the bug must be: when reporting more than one point at the same time,
make sure their mnc's are accurately recorded: they might not always be
the same!

Here is a similar patch of two cells for each interval, but the mnc bug
is not revealed, because they are both the same mnc:

```
466,92,10309,20259455,8831,309,392,5,-103,,24.60019500,121.87322000,2.6,233.76,149.95,6142,"2023-05-09T01:41:53.098Z",UMTS,false,"2023-05-09T01:40:58.411Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,3087
466,92,10391,25633523,8947,391,251,0,-113,,24.60019500,121.87322000,2.6,233.76,149.95,6142,"2023-05-09T01:41:53.098Z",UMTS,true,"2023-05-09T01:41:09.090Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,,3087
466,92,10309,20259455,8831,309,392,5,-103,,24.59837500,121.87437000,2.4,233.39,150.09,6152,"2023-05-09T01:41:54.087Z",UMTS,false,"2023-05-09T01:40:58.411Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,3087
466,92,10391,25633523,8947,391,251,0,-113,,24.59837500,121.87437000,2.4,233.39,150.09,6152,"2023-05-09T01:41:54.087Z",UMTS,true,"2023-05-09T01:41:09.090Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,,3087
466,92,10309,20259455,8831,309,392,5,-103,,24.596533333333,121.875531666667,2.6,234.4,150.18,6164.6,"2023-05-09T01:41:55.097Z",UMTS,false,"2023-05-09T01:40:58.411Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,3087
466,92,10391,25633523,8947,391,251,0,-113,,24.596533333333,121.875531666667,2.6,234.4,150.18,6164.6,"2023-05-09T01:41:55.097Z",UMTS,true,"2023-05-09T01:41:09.090Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,,3087
466,92,10309,20259455,8831,309,392,5,-103,,24.59469500,121.876686666667,2.6,235.11,149.92,6177,"2023-05-09T01:41:56.087Z",UMTS,false,"2023-05-09T01:40:58.411Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,0,3087
466,92,10391,25633523,8947,391,251,0,-113,,24.59469500,121.876686666667,2.6,235.11,149.92,6177,"2023-05-09T01:41:56.087Z",UMTS,true,"2023-05-09T01:41:09.090Z","samsung SM-A136U",,,,,,,,,,,,,,,,,,,3087
```

**Comment by zamojski** [comment] 2023-09-28 09:19
There's no way to determine which values are correct... Which version of API do you use in Advanced Preferences?

**Comment by jidanni** [comment] 2023-09-29 08:27
I use "Auto detect".

But what number that equals isn't shown in the app anywhere.

**Comment by zamojski** [comment] 2024-08-28 20:33
I believe that radio firmware doesn't update all values transactionally and it causes the issue. Closing as cannot reproduce.

**Closed by zamojski** 2024-08-28 20:33 UTC
Labels: help wanted
